version: "3"
services:
  node:
    container_name: node
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    links:
      - mongo
    command: npm run start:dev

  mongo:
    container_name: mongo
    image: mongo
#    volumes:
#      - ./mongodata:/data/db
    ports:
      - 27017:27017